### ISSUE TITLE
How to use proxyserver(for example IP: 122.85.789.11 ,port:8080,username:"username",password:"abcd$456") to open captcha harvest window instead of use localhost proxy

### ISSUE THREAD

**Issue by Developer-Dat** [u1aryz/z-captcha#2]
I am new in electron.I have tested proxy server instead of use localhost but no captcha shown in captcha window. only white screen I think there is some error to open captcha.html because no back button shown in window.I don't no how to debug this.Could you please take a look into this issue

**Comment by u1aryz** [comment]
This app works by hooking on localhost and returning another html.
